DEFAULT_SEED =  1  

SAMPLING_PROB =  0.9
SAMPLING_PROB_MISTRAL = 0.7
SAMPLING_TEMP =  1.  

SAMPLE_LENGTH_TITLE = 64 
SAMPLE_LENGTH_PLACE = 512
SAMPLE_LENGTH = 1024
SAMPLE_LENGTH_SONNET = 2048 

MAX_PARAGRAPH_LENGTH_CHARACTERS = 1024
MAX_PARAGRAPH_LENGTH_SCENES = 1024
MAX_PARAGRAPH_LENGTH_SCENES_MISTRAL = 700
MAX_PARAGRAPH_LENGTH = 3000

MAX_RETRIES = 10 

MAX_NUM_REPETITIONS = 4 
MAX_NUM_ATTEMPTS_GET_OUT_OF_LOOP = 4

MAX_RETRIES = 10
TIMEOUT = 120.0


END_MARKER = '**END**'
STOP_MARKER = '\n'
CHARACTER_MARKER = '**Character:** '
DESCRIPTION_MARKER = '**Description:** '
SCENES_MARKER = '**Scenes:**'
DIALOG_MARKER = '**Dialog:**'
LOGLINE_MARKER = "**Logline:** "
TITLE_ELEMENT = 'Title: '
CHARACTERS_ELEMENT = 'Characters: '
DESCRIPTION_ELEMENT = 'Description: '
PLACE_ELEMENT = 'Place: '
PLOT_ELEMENT = 'Plot element: '
PREVIOUS_ELEMENT = 'Previous beat: '
SUMMARY_ELEMENT = 'Summary: '
BEAT_ELEMENT = 'Beat: '
LOGLINE_ELEMENT = "Logline: "

